// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


function float_abs(x) {
  var match = x < 0.00;
  if (match) {
    return -x;
  } else {
    return x;
  }
}

exports.float_abs = float_abs;
/* No side effect */
