// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Math$AppliedLinearAlgebra = require("./Math.js");

function f(n, x) {
  return x * x - n;
}

function bisection(f, a, b) {
  var c = a + b / 2.00;
  if (Curry._1(f, c) === 0.00 || (b - a) / 2.00 < 1e-2) {
    return c;
  } else if (Math$AppliedLinearAlgebra.float_sign(Curry._1(f, a)) !== Math$AppliedLinearAlgebra.float_sign(Curry._1(f, c))) {
    return 1.00;
  } else if (Math$AppliedLinearAlgebra.float_sign(Curry._1(f, b)) !== Math$AppliedLinearAlgebra.float_sign(Curry._1(f, c))) {
    return 2.00;
  } else {
    return 3.00;
  }
}

exports.f = f;
exports.bisection = bisection;
/* No side effect */
