// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function vector_add($staropt$star, l1, l2) {
  var i = $staropt$star !== undefined ? $staropt$star : 0;
  if (l1) {
    return /* :: */[
            l1[0] + List.nth(l2, i),
            vector_add(i + 1 | 0, l1[1], l2)
          ];
  } else {
    return /* [] */0;
  }
}

function vector_substract($staropt$star, l1, l2) {
  var i = $staropt$star !== undefined ? $staropt$star : 0;
  if (l1) {
    return /* :: */[
            l1[0] - List.nth(l2, i),
            vector_substract(i + 1 | 0, l1[1], l2)
          ];
  } else {
    return /* [] */0;
  }
}

function add_one(l) {
  if (l) {
    return /* :: */[
            l[0] + 1 | 0,
            add_one(l[1])
          ];
  } else {
    return /* [] */0;
  }
}

exports.vector_add = vector_add;
exports.vector_substract = vector_substract;
exports.add_one = add_one;
/* No side effect */
