// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function add($staropt$star, v1, v2) {
  var i = $staropt$star !== undefined ? $staropt$star : 0;
  if (v1) {
    return /* :: */[
            v1[0] + List.nth(v2, i),
            add(i + 1 | 0, v1[1], v2)
          ];
  } else {
    return /* [] */0;
  }
}

function substract($staropt$star, v1, v2) {
  var i = $staropt$star !== undefined ? $staropt$star : 0;
  if (v1) {
    return /* :: */[
            v1[0] - List.nth(v2, i),
            substract(i + 1 | 0, v1[1], v2)
          ];
  } else {
    return /* [] */0;
  }
}

function scale($staropt$star, n, v) {
  var i = $staropt$star !== undefined ? $staropt$star : 0;
  if (v) {
    return /* :: */[
            v[0] * n,
            scale(i + 1 | 0, n, v[1])
          ];
  } else {
    return /* [] */0;
  }
}

exports.add = add;
exports.substract = substract;
exports.scale = scale;
/* No side effect */
