// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Math$LinearAlgebraRe = require("../src/Math.js");

describe("Math absolute value from floating number utility", (function () {
        Jest.test("positive number", (function (param) {
                return Jest.Expect[/* toEqual */12](10.00, Jest.Expect[/* expect */0](Math$LinearAlgebraRe.float_abs(10.00)));
              }));
        Jest.test("negative number", (function (param) {
                return Jest.Expect[/* toEqual */12](10.00, Jest.Expect[/* expect */0](Math$LinearAlgebraRe.float_abs(-10.00)));
              }));
        Jest.test("negative number", (function (param) {
                return Jest.Expect[/* toEqual */12](1.85, Jest.Expect[/* expect */0](Math$LinearAlgebraRe.float_abs(-1.85)));
              }));
        return Jest.test("positive number", (function (param) {
                      return Jest.Expect[/* toEqual */12](12.33, Jest.Expect[/* expect */0](Math$LinearAlgebraRe.float_abs(12.33)));
                    }));
      }));

describe("number sign proof function", (function () {
        Jest.test("negative number", (function (param) {
                return Jest.Expect[/* toEqual */12](-1.00, Jest.Expect[/* expect */0](Math$LinearAlgebraRe.float_sign(-3.00)));
              }));
        return Jest.test("positive number", (function (param) {
                      return Jest.Expect[/* toEqual */12](1.00, Jest.Expect[/* expect */0](Math$LinearAlgebraRe.float_sign(3.00)));
                    }));
      }));

describe("radians to degrees", (function () {
        Jest.test("150 radians", (function (param) {
                return Jest.Expect[/* toEqual */12](8594.366926962348, Jest.Expect[/* expect */0](Math$LinearAlgebraRe.rad_to_deg(150.00)));
              }));
        return Jest.test("-45 radias", (function (param) {
                      return Jest.Expect[/* toEqual */12](-2291.831180523293, Jest.Expect[/* expect */0](Math$LinearAlgebraRe.rad_to_deg(-40.00)));
                    }));
      }));

/*  Not a pure module */
