// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';


function float_abs(x) {
  var match = x < 0.00;
  if (match) {
    return -x;
  } else {
    return x;
  }
}

function float_sign(n) {
  var match = n < 0.00;
  if (match) {
    return -1.00;
  } else {
    return 1.00;
  }
}

function rad_to_deg(r) {
  return r * (180.00 / 3.141592653589793);
}

exports.float_abs = float_abs;
exports.float_sign = float_sign;
exports.rad_to_deg = rad_to_deg;
/* No side effect */
