// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Math$AppliedLinearAlgebra = require("./Math.js");

function f(v, n) {
  return n * n - v;
}

function bisection(_$staropt$star, f, _l, _h) {
  while(true) {
    var h = _h;
    var l = _l;
    var $staropt$star = _$staropt$star;
    var i = $staropt$star !== undefined ? $staropt$star : 0;
    var m = (l + h) / 2.00;
    if (Curry._1(f, m) === 0.00 || (h - l) / 2.00 < 1e-15) {
      return m;
    } else if (Math$AppliedLinearAlgebra.float_sign(Curry._1(f, l)) !== Math$AppliedLinearAlgebra.float_sign(Curry._1(f, m))) {
      _h = m;
      _$staropt$star = i + 1 | 0;
      continue ;
    } else if (Math$AppliedLinearAlgebra.float_sign(Curry._1(f, h)) !== Math$AppliedLinearAlgebra.float_sign(Curry._1(f, m))) {
      _l = m;
      _$staropt$star = i + 1 | 0;
      continue ;
    } else {
      return m;
    }
  };
}

exports.f = f;
exports.bisection = bisection;
/* No side effect */
